imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    seo_title: Service Taxi Flevoland
    seo_description: Service Taxi Flevoland is een allround taxibedrijf, gevestigd in Flevoland. Onze chauffeurs hebben verschillende achtergronden in de taxibranche en jarenlang ervaring.
    locale: nl

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - AppBundle:forms:_fields.html.twig

assetic:
    filters:
      uglifyjs2:
        bin: node_modules/.bin/uglifyjs
      uglifycss:
        bin: node_modules/.bin/uglifycss
        node: null
      cssrewrite: ~
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
      - AppBundle
    assets:
      font-awesome-woff2:
        inputs: '@AppBundle/Resources/public/vendor/components-font-awesome/fonts/fontawesome-webfont.woff2'
        output: 'fonts/fontawesome-webfont.woff2'
      font-awesome-woff:
        inputs: '@AppBundle/Resources/public/vendor/components-font-awesome/fonts/fontawesome-webfont.woff'
        output: 'fonts/fontawesome-webfont.woff'
      font-awesome-ttf:
        inputs: '@AppBundle/Resources/public/vendor/components-font-awesome/fonts/fontawesome-webfont.ttf'
        output: 'fonts/fontawesome-webfont.ttf'
      font-awesome-svg:
        inputs: '@AppBundle/Resources/public/vendor/components-font-awesome/fonts/fontawesome-webfont.svg'
        output: 'fonts/fontawesome-webfont.svg'
      font-awesome-eot:
        inputs: '@AppBundle/Resources/public/vendor/components-font-awesome/fonts/fontawesome-webfont.eot'
        output: 'fonts/fontawesome-webfont.eot'
      font-awesome:
        inputs: '@AppBundle/Resources/public/vendor/components-font-awesome/fonts/FontAwesome.otf'
        output: 'fonts/FontAwesome.otf'
      gliphicons-woff2:
        inputs: '@AppBundle/Resources/public/vendor/bootstrap/fonts/glyphicons-halflings-regular.woff2'
        output: 'fonts/glyphicons-halflings-regular.woff2'
      gliphicons-woff:
        inputs: '@AppBundle/Resources/public/vendor/bootstrap/fonts/glyphicons-halflings-regular.woff'
        output: 'fonts/glyphicons-halflings-regular.woff'
      gliphicons-ttf:
        inputs: '@AppBundle/Resources/public/vendor/bootstrap/fonts/glyphicons-halflings-regular.ttf'
        output: 'fonts/glyphicons-halflings-regular.ttf'
      gliphicons-svg:
        inputs: '@AppBundle/Resources/public/vendor/bootstrap/fonts/glyphicons-halflings-regular.svg'
        output: 'fonts/glyphicons-halflings-regular.svg'
      gliphicons-eot:
        inputs: '@AppBundle/Resources/public/vendor/bootstrap/fonts/glyphicons-halflings-regular.eot'
        output: 'fonts/glyphicons-halflings-regular.eot'


# Doctrine Configuration
#doctrine:
#    dbal:
#        driver: pdo_mysql
#        host: '%database_host%'
#        port: '%database_port%'
#        dbname: '%database_name%'
#        user: '%database_user%'
#        password: '%database_password%'
#        charset: UTF8
#        # if using pdo_sqlite as your database driver:
#        #   1. add the path in parameters.yml
#        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
#        #   2. Uncomment database_path in parameters.yml.dist
#        #   3. Uncomment next line:
#        #path: '%database_path%'
#
#    orm:
#        auto_generate_proxy_classes: '%kernel.debug%'
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
#    auth_mode:  '%mailer_auth_mode%'
    host:      '%mailer_host%'
    port:      '%mailer_port%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    auth_mode: '%mailer_auth_mode%'

cmf_seo:
    title: '%seo_title%'
    description: '%seo_description%'
    sitemap:
        enabled: false
    content_listener:
        enabled: false

sonata_seo:
    page:
        title: '%seo_title%'
        metas:
            name:
                description: '%seo_description%'
                keywords: taxi, flevoland, service, thuisbrengservice, vervoor, zakelijk, chaffeurs, koeriersdiensten, groepsvervoer
